BookStore.Web/Controllers/BookController.cs
using BookStore.Domain.Domain;
using BookStore.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly IBookService _bookService;

        public BookController(IAuthorService authorService, IBookService bookService)
        {
            _authorService = authorService;
            _bookService = bookService;
        }

        public IActionResult Index()
        {
            var books = _bookService.GetAll();
            return View(books);
        }

        // GET: Books/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookService.GetDetails(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            var authors = _authorService.GetAll();
            ViewBag.AuthorId = authors.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name
            }).ToList();
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Title,Description,AuthorId,Image,Id")] Book book)
        {
            book.Id = Guid.NewGuid();
            book.BookPublishers = new List<BookPublisher>();
            _bookService.CreateNew(book);
            return RedirectToAction(nameof(Index));
        }

        // GET: Books/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookService.GetDetails(id);
            if (book == null)
            {
                return NotFound();
            }

            var authors = _authorService.GetAll();
            ViewBag.AuthorId = authors.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name
            }).ToList();

            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Title,Description,AuthorId,Image,Id")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

      
            try
            {
               _bookService.UpdateExisting(book);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BookExists(book.Id))
                {
                   return NotFound();
                }
                else
                {
                   throw;
                }
            }
            return RedirectToAction(nameof(Index));
            
        }

        // GET: Books/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = _bookService.GetDetails(id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var book = _bookService.GetDetails(id);
            if (book != null)
            {
                _bookService.Delete(id);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(Guid id)
        {
            return _bookService.GetDetails(id) != null;
        }
    }
}

BookStore.Web/Controllers/BookPublisherController.cs
using BookStore.Domain.Domain;
using BookStore.Domain.DTO;
using BookStore.Service.Implementation;
using BookStore.Service.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net.Sockets;
using System.Security.Claims;

namespace BookStore.Web.Controllers
{
    public class BookPublisherController : Controller
    {
        private readonly IBookPublisherService _bookPublisherService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IBookService _bookService;
        private readonly IPublisherService _publisherService;

        public BookPublisherController(IBookPublisherService bookPublisherService, IShoppingCartService shoppingCartService, IBookService bookService, IPublisherService publisherService)
        {
            _bookPublisherService = bookPublisherService;
            _shoppingCartService = shoppingCartService;
            _bookService = bookService;
            _publisherService = publisherService;
        }





        // GET: Tickets
        public IActionResult Index()
        {
            return View(_bookPublisherService.GetAll());
        }

        // GET: Tickets/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tmp = _bookPublisherService.GetDetails(id);

            if (tmp == null)
            {
                return NotFound();
            }

            return View(tmp);
        }

        // GET: Tickets/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.BookId = new SelectList(_bookService.GetAll(), "Id", "Title");
            ViewBag.PublisherId = new SelectList(_publisherService.GetAll(), "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Create([Bind("Id,BookId,PublisherId,Price")] BookPublisher bookPublisher)
        {
            if (ModelState.IsValid)
            {
                _bookPublisherService.CreateNew(bookPublisher);
                return RedirectToAction(nameof(Index));
            }
            return View(bookPublisher);
        }

        // GET: Tickets/Edit/5
        [Authorize]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tmp = _bookPublisherService.GetDetails(id);
            if (tmp == null)
            {
                return NotFound();
            }
            var books = _bookService.GetAll();
            ViewBag.BookId = books.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Title
            }).ToList();
            var publishers = _publisherService.GetAll();
            ViewBag.PublisherId = publishers.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name
            }).ToList();
            return View(tmp);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Guid id, [Bind("Id,BookId,PublisherId,Price")] BookPublisher bookPublisher)
        {
            if (id != bookPublisher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _bookPublisherService.UpdateExisting(bookPublisher);
                return RedirectToAction(nameof(Index));
            }
            return View(bookPublisher);
        }

        // GET: Tickets/Delete/5
        [Authorize]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tmp = _bookPublisherService.GetDetails(id);
            if (tmp == null)
            {
                return NotFound();
            }

            return View(tmp);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _bookPublisherService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        [Authorize]

        public IActionResult AddProductToCart(Guid Id)
        {
            var result = _shoppingCartService.getProductInfo(Id);
            if (result != null)
            {
                return View(result);
            }
            return View();
        }

        [HttpPost]
        public IActionResult AddProductToCart(AddToCartDTO model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var result = _shoppingCartService.AddProductToShoppingCart(userId, model);

            if (result != null)
            {
                return RedirectToAction("Index", "ShoppingCarts");
            }
            else { return View(model); }
        }


    }
}

BookStore.Web/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore.Repository;
using BookStore.Domain.Domain;
using BookStore.Repository.Interface;
using BookStore.Service.Interface;

namespace WebApplication1.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherService _publisherService;
        private readonly IBookService _bookService;

        public PublisherController(IPublisherService publisherService, IBookService bookService)
        {
            _publisherService = publisherService;
            _bookService = bookService;
        }

        // GET: Publishers
        public IActionResult Index()
        {
            var publishers = _publisherService.GetAll();
            return View(publishers);
        }

        // GET: Publishers/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = _publisherService.GetDetails(id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            var books = _bookService.GetAll();
            ViewBag.BookId = books.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Title
            }).ToList();

            var publishers = _publisherService.GetAll();
            ViewBag.PublisherId = publishers.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name
            }).ToList();
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Name,Country,Address,Id")] Publisher publisher)
        {

            publisher.Id = Guid.NewGuid();
            publisher.BookPublishers = new List<BookPublisher>();
            _publisherService.CreateNew(publisher);
            return RedirectToAction(nameof(Index));

        }

        // GET: Publishers/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = _publisherService.GetDetails(id);

            if (publisher == null)
            {
                return NotFound();
            }

            var books = _bookService.GetAll();
            ViewBag.BookId = books.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Title
            }).ToList();

            var publishers = _publisherService.GetAll();
            ViewBag.PublisherId = publishers.Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name
            }).ToList();

            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Name,Country,Address,Id")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }


            try
            {
                _publisherService.UpdateExisting(publisher);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PublisherExists(publisher.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));

        }

        // GET: Publishers/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = _publisherService.GetDetails(id);

            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var publisher = _publisherService.GetDetails(id);
            if (publisher != null)
            {
                _publisherService.Delete(id);
            }

            return RedirectToAction(nameof(Index));
        }

        private bool PublisherExists(Guid id)
        {
            return _publisherService.GetDetails(id) != null;
        }
    }
}

BookStore.Web/Views/BookPublisher/AddProductToCart.cshtml
@model BookStore.Domain.DTO.AddToCartDTO



<div class="container w-50 mx-auto shadow-lg text-center p-3 mb-5 bg-body-tertiary rounded-4">
    <h1 class="display-5">Add to Cart</h1>
    <hr class="border-3 rounded-3 mx-auto" style="width:150px" />
    <div class="row">
        <div class="col w-75 mx-auto">
            <form method="post" asp-action="AddProductToCart">
                <input type="hidden" asp-for="SelectedProductId" value="@Model.SelectedProductId" class="form-control" />
                <div class="row mt-4">
                    <div class="form-group">
                        <label asp-for="SelectedProductName" class="control-label"></label>
                        <input asp-for="SelectedProductName" class="form-control" />
                        <span asp-validation-for="SelectedProductName" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mt-4">
                    <div class="form-group">
                        <label asp-for="Quantity" class="control-label"></label>
                        <input asp-for="Quantity" type="number" class="form-control" />
                        <span asp-validation-for="Quantity" class="text-danger"></span>
                    </div>
                </div>

                
                    <button type="submit" class="btn btn-success px-4 mt-3">Add To Cart</button>
              
            </form>
            
        </div>
    </div>

    <div>
        <a asp-action="Index" class=" btn btn-dark m-2">Back to List</a>
    </div>

</div>

BookStore.Web/Views/BookPublisher/Create.cshtml
@model BookStore.Domain.Domain.BookPublisher
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container w-50 mx-auto shadow-lg text-center p-3 mb-5 bg-body-tertiary rounded-4">
    <h1 class="display-5">Create BookPublisher</h1>
    <hr class="border-3 rounded-3 mx-auto" style="width:150px" />
    <div class="row">
        <div class="col w-75 mx-auto">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="BookId" class="control-label">Book</label>
                    <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="PublisherId" class="control-label">Publisher</label>
                    <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary m-2" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index" class=" btn btn-dark m-2">Back to List</a>
    </div>

</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStore.Web/Views/BookPublisher/Delete.cshtml
@model BookStore.Domain.Domain.BookPublisher

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container w-50 p-5 mx-auto shadow-lg mb-5 bg-body-tertiary rounded-4">
    <h1 class="display-5 text-center ">Delete BookPublisher</h1>
    <hr class="border-3 rounded-3 mx-auto" style="width:150px" />
    <div class="row">
        <div class="col w-75 mx-auto">
            <h4 class="text-center ">Are you sure you want to delete this?</h4>
            <div>

                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Book.Title)
                    </dt>
                    <dd class="col-sm-10">
                        <h2>@Html.DisplayFor(model => model.Book.Title)</h2>
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Publisher)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Publisher.Name)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Price)
                    </dt>
                    <dd class="col-sm-10 fw-bolder">
                        @Html.DisplayFor(model => model.Price).00 MKD
                    </dd>
                </dl>

                <form asp-action="Delete" class="text-center">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Delete" class="btn text-center btn-danger m-2" />
                </form>
            </div>
        </div>
    </div>

    <div class="text-center">
        <a asp-action="Index" class=" btn btn-dark m-2">Back to List</a>
    </div>

</div>

BookStore.Web/Views/BookPublisher/Details.cshtml
@model BookStore.Domain.Domain.BookPublisher

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row w80 mx-auto">
    <div class="col-md-4">
        <img src="@Model.Book.Image" class="" style="height:420px;width:300px" alt="...">
    </div>
    <div class="col-md-8">
        <h1 class="display-5 text-center my-2" style="color:#1A4D2E">Details for BookPublisher</h1>
        <hr class="border-3 rounded-3 mx-auto" style="width:200px" />
        <dl class="row">
            <h2> @Html.DisplayFor(model => model.Book.Title)</h2>


            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Publisher)
            </dt>
            <dd class="col-sm-10">
                <a class="text-dark  fw-bolder" asp-controller="Publisher" asp-action="Details" asp-route-id="@Model.Publisher.Id">@Model.Publisher.Name</a>
            </dd>
            <dt class="col-sm-2">
                <h4>Price</h4>
            </dt>
            <dd class="col-sm-10">
                <h2> @Html.DisplayFor(model => model.Price).00 MKD</h2>
            </dd>
            <a asp-controller="BookPublisher" class="btn my-3 btn-success px-3" asp-action="AddProductToCart" asp-route-id="@Model.Id">Add To Cart</a>
            <div class="my-3">
                <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.Id">Edit</a> | 
                <a asp-action="Index" class="btn btn-dark">Back to List</a> | 
                <a asp-action="Delete" asp-route-id="@Model?.Id" class="btn btn-danger">Delete</a>
            </div>
        </dl>
    </div>


</div>

BookStore.Web/Views/BookPublisher/Edit.cshtml
@model BookStore.Domain.Domain.BookPublisher

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container w-50 mx-auto shadow-lg text-center p-3 mb-5 bg-body-tertiary rounded-4">
    <h1 class="display-5">Edit BookPublisher</h1>
    <hr class="border-3 rounded-3 mx-auto" style="width:150px" />
    <div class="row">
        <div class="col w-75 mx-auto">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="BookId" class="control-label"></label>
                    <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                    <span asp-validation-for="BookId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PublisherId" class="control-label"></label>
                    <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
                    <span asp-validation-for="PublisherId" class="text-danger"></span>
                </div>
               
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary m-2" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index" class=" btn btn-dark m-2">Back to List</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStore.Web/Views/BookPublisher/Index.cshtml
@model IEnumerable<BookStore.Domain.Domain.BookPublisher>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-5 text-center" style="color:#1A4D2E">Аvailable Books</h1>
<hr class="border-3 rounded-3 mx-auto" style="width:200px" />

<div class="row mx-auto w-75 mx-auto row-cols-1 row-cols-md-3 mb-5 g-4">
    @foreach (var item in Model)
    {
        <div class="col my-4 ">
            <div class="card text-center  h-100 " style="width: 17rem;">
                <img src="@item.Book.Image" class="card-img-top " style="height:58%" alt="...">
                <div class="card-body">
                    <a asp-controller="Book" style="text-decoration:none" class="text-dark " asp-action="Details" asp-route-id="@item.Book.Id"><h4 class="card-title">@item.Book.Title</h4> </a>
                    <p class="card-text">Publisher: <a asp-controller="Publisher" class="text-dark fw-bolder" asp-action="Details" asp-route-id="@item.Publisher.Id">@item.Publisher.Name</a></p>
                </div>
                <div class="card-footer">
                    <h3 class="py-2">@item.Price.00 MKD</h3>
                    <a asp-controller="BookPublisher" class="btn btn-dark" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    <a asp-controller="BookPublisher" class="btn btn-success px-3" asp-action="AddProductToCart" asp-route-id="@item.Id">Add To Cart</a>
                </div>
            </div>
        </div>

    }

</div>
<a asp-controller="BookPublisher" class="btn mx-auto d-block w-25 my-3 btn-success" asp-action="Create">Create New</a>




   

        
    

</div>